// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Explicare
{
    internal sealed partial class Vsix
    {
        public const string Id = "Explicare.4d35ba46-a641-448c-bf23-456304bc9a1f";
        public const string Name = "Explicare";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Georg Piwonka";
        public const string Tags = "";
    }
}
